# image will be published to ghcr.io/<user>/<name>
name: nhubaotruong-ublue
# description will be included in the image's metadata
description: nhubaotruong uBlue image

# the base image to build on top of (FROM) and the version tag to use
base-image: ghcr.io/ublue-os/silverblue-main
image-version: 41 # latest is also supported if you want new updates ASAP

# module configuration, executed in order
# you can include multiple instances of the same module
modules:
  - type: files
    files:
      - source: files
        destination: /

  - type: containerfile
    containerfiles:
      - replace-kernel
      # - install-akmods
      # - zfs-rpms
  # - upgrade
  # - match-kernel-version

  - type: rpm-ostree
    install:
      - https://mirrors.rpmfusion.org/free/fedora/rpmfusion-free-release-%OS_VERSION%.noarch.rpm
      - https://mirrors.rpmfusion.org/nonfree/fedora/rpmfusion-nonfree-release-%OS_VERSION%.noarch.rpm

  - type: akmods
    base: bazzite
    install:
      - openrazer
      - v4l2loopback
      - xone
      - xpadneo
      # - VirtualBox

  - type: rpm-ostree
    repos:
      - https://raw.githubusercontent.com/coreos/fedora-coreos-config/testing-devel/fedora-coreos-pool.repo
      - https://copr.fedorainfracloud.org/coprs/atim/starship/repo/fedora-%OS_VERSION%/atim-starship-fedora-%OS_VERSION%.repo
      - https://copr.fedorainfracloud.org/coprs/ublue-os/staging/repo/fedora-%OS_VERSION%/ublue-os-staging-fedora-%OS_VERSION%.repo
      - https://copr.fedorainfracloud.org/coprs/ycollet/audinux/repo/fedora-%OS_VERSION%/ycollet-audinux-fedora-%OS_VERSION%.repo
      - https://copr.fedorainfracloud.org/coprs/kylegospo/bazzite/repo/fedora-%OS_VERSION%/kylegospo-bazzite-fedora-%OS_VERSION%.repo
      - https://copr.fedorainfracloud.org/coprs/ganto/lxc4/repo/fedora-%OS_VERSION%/ganto-lxc4-fedora-%OS_VERSION%.repo
      - https://download.opensuse.org/repositories/home:/lamlng/Fedora_Rawhide/home:lamlng.repo
      - https://openrazer.github.io/hardware:razer.repo
      - https://pkgs.tailscale.com/stable/fedora/tailscale.repo
      - https://packages.microsoft.com/config/rhel/8/insiders-slow.repo
      - https://copr.fedorainfracloud.org/coprs/kylegospo/bazzite-multilib/repo/fedora-%OS_VERSION%/kylegospo-bazzite-multilib-fedora-%OS_VERSION%.repo?arch=x86_64
      - https://copr.fedorainfracloud.org/coprs/bieszczaders/kernel-cachyos-addons/repo/fedora-%OS_VERSION%/bieszczaders-kernel-cachyos-addons-fedora-%OS_VERSION%.repo
      # - https://copr.fedorainfracloud.org/coprs/rodoma92/rmlint/repo/fedora-%OS_VERSION%/rodoma92-rmlint-fedora-%OS_VERSION%.repo
      # - https://copr.fedorainfracloud.org/coprs/eyecantcu/supergfxctl/repo/fedora-%OS_VERSION%/eyecantcu-supergfxctl-fedora-%OS_VERSION%.repo
      # - https://download.docker.com/linux/fedora/docker-ce.repo
    install:
      - sqlite
      - starship
      - gnome-tweaks
      # - tlp
      - neovim
      - zstd
      - ibus-bamboo
      - ibus-unikey
      - tailscale
      - breeze-cursor-theme
      - i2c-tools
      - ddcutil
      # - qemu
      - qemu-user-binfmt
      - qemu-user-static
      # - libvirt
      # - libvirt-nss
      - edk2-ovmf
      - zram-generator
      - zsh
      - igt-gpu-tools
      - libgda
      - libgda-sqlite
      - firewall-config
      - dejavu-sans-fonts
      - dejavu-serif-fonts
      - liberation-fonts
      - ufraw
      - duperemove
      - rmlint
      - python3-icoextract
      - gnome-directory-thumbnailer
      - gnome-epub-thumbnailer
      - gnome-kra-ora-thumbnailer
      - waydroid
      - lxc
      - lxc-libs
      - cage
      - wlr-randr
      # - podman-docker
      - nautilus-open-any-terminal
      - usbguard
      - usbguard-dbus
      - usbguard-tools
      - fuse-sshfs
      - openssh-askpass
      - nautilus-gsconnect
      - ifuse
      - libimobiledevice
      - usbmuxd
      - wl-clipboard
      - xclip
      - bindfs
      - powertop
      - foo2zjs
      - mdatp
      - bootc
      - rsms-inter-vf-fonts
      - cpulimit
      - kernel-tools
      - scx-scheds
      - fontawesome-fonts-all
      - profile-cleaner
      - samba-dcerpc
      - samba-ldb-ldap-modules
      - samba-winbind-clients
      - samba-winbind-modules
      - samba
      - yq
      - printer-driver-brlaser
      - epson-inkjet-printer-escpr
      - epson-inkjet-printer-escpr2
      - dnscrypt-proxy
      - openresolv
      - python-pysocks
      - openrazer-daemon
      - python3-openrazer
      - fuse-btfs
      # Gnome extensions
      - gnome-shell-extension-gsconnect
      - gnome-shell-extension-appindicator
      - gnome-shell-extension-user-theme
      - gnome-shell-extension-dash-to-dock
      - gnome-shell-extension-just-perfection
      - gnome-shell-extension-caffeine
    remove:
      - firefox # default firefox removed in favor of flatpak
      - firefox-langpacks # langpacks needs to also be removed to prevent dependency problems
      - tuned-ppd # Prevent Gnome from talking to tuned
      - yelp
      - gnome-tour
      - toolbox
      - gnome-software
      - zram-generator-defaults
      - gnome-classic-session
      - thermald
      - systemd-networkd
      - ptyxis
    optfix:
      - teamviewer
      - microsoft
    replace:
      - from-repo: https://copr.fedorainfracloud.org/coprs/trixieua/mutter-patched/repo/fedora-%OS_VERSION%/trixieua-mutter-patched-fedora-%OS_VERSION%.repo
        packages:
          - mutter
          - mutter-common
          - gnome-shell
          - xorg-x11-server-Xwayland
      # - from-repo: https://copr.fedorainfracloud.org/coprs/ublue-os/staging/repo/fedora-%OS_VERSION%/ublue-os-staging-fedora-%OS_VERSION%.repo
      #   packages:
      #     - mutter
      #     - mutter-common
      #     - gnome-shell
      #     - fwupd
      #     - fwupd-plugin-flashrom
      #     - fwupd-plugin-modem-manager
      #     - fwupd-plugin-uefi-capsule-data
      #   - from-repo: https://copr.fedorainfracloud.org/coprs/kylegospo/bazzite-multilib/repo/fedora-%OS_VERSION%/kylegospo-bazzite-multilib-fedora-%OS_VERSION%.repo
      #     packages:
      #       # - mesa-filesystem
      #       # - mesa-libxatracker
      #       # - mesa-libglapi
      #       # - mesa-dri-drivers
      #       # - mesa-libgbm
      #       # - mesa-libEGL
      #       # - mesa-vulkan-drivers
      #       # - mesa-libGL
      #       # - pipewire
      #       # - pipewire-alsa
      #       # - pipewire-gstreamer
      #       # - pipewire-jack-audio-connection-kit
      #       # - pipewire-jack-audio-connection-kit-libs
      #       # - pipewire-libs
      #       # - pipewire-pulseaudio
      #       # - pipewire-utils
      #       # - pipewire-plugin-libcamera
      #       # - bluez
      #       # - bluez-obexd
      #       # - bluez-cups
      #       # - bluez-libs
      #       - xorg-x11-server-Xwayland
      - from-repo: https://copr.fedorainfracloud.org/coprs/sentry/switcheroo-control_discrete/repo/fedora-%OS_VERSION%/sentry-switcheroo-control_discrete-fedora-%OS_VERSION%.repo
        packages:
          - switcheroo-control
    #   # - from-repo: https://copr.fedorainfracloud.org/coprs/kylegospo/bazzite/repo/fedora-%OS_VERSION%/kylegospo-bazzite-fedora-%OS_VERSION%.repo
    #   #   packages:
    #   #     - amd-gpu-firmware
    #   #     - amd-ucode-firmware
    #   #     - atheros-firmware
    #   #     - brcmfmac-firmware
    #   #     - cirrus-audio-firmware
    #   #     - intel-audio-firmware
    #   #     - intel-gpu-firmware
    #   #     - iwlegacy-firmware
    #   #     - iwlwifi-dvm-firmware
    #   #     - iwlwifi-mvm-firmware
    #   #     - libertas-firmware
    #   #     - linux-firmware
    #   #     - linux-firmware-whence
    #   #     - mt7xxx-firmware
    #   #     - nvidia-gpu-firmware
    #   #     - nxpwireless-firmware
    #   #     - realtek-firmware
    #   #     - tiwilink-firmware

  - from-file: flatpak.yml

  - type: gschema-overrides
    include:
      - zz1-desktop.gschema.override

  # - type: fonts
  #   fonts:
  #     nerd-fonts:
  #       - FiraCode
  #       - Meslo
  #       - CascadiaCode

  # - type: yafti # if included, yafti and it's dependencies (pip & libadwaita) will be installed and set up
  #   custom-flatpaks:
  # this section is optional
  # - Celluloid: io.github.celluloid_player.Celluloid
  # - Krita: org.kde.krita

  - type: bling # configure what to pull in from ublue-os/bling
    install:
      - ublue-update # https://github.com/ublue-os/ublue-update

  - type: gnome-extensions
    install:
      - "615" # AppIndicator and KStatusNotifierItem Support
      # - "1319" # GSConnect
      - "19" # User Themes
      - "307" # Dash to Dock
      - "7" # Removable Drive Menu
      - "3843" # Just Perfection
      - "517" # Caffeine
      - "4269" # Alphabetical App Grid
      - "2594" # Always Indicator
      # - "5425" # Battery Time
      - "6670" # Bluetooth Battery Meter
      - "2645" # Brightness Control Using ddcutil
      # - "1873" # Disable Unredirect Fullscreen Windows
      # - "4485" # Favourites In AppGrid
      # - "4158" # Gnome 4x UI Improvements
      - "3956" # Gnome fuzzy app search
      - "6940" # Media Progress
      # - "5278" # Pano Clipboard Manager
      - "4691" # Pip on top
      - "5964" # Quick Settings Audio Devices Hider
      - "5660" # Weather Or Not
      - "4798" # Thinkpad Battery Threshold
      - "6807" # System Monitor

  # - type: brew
  #   brew-analytics: false

  - type: script
    scripts:
      - nerd-fonts.sh
      - byedpi.sh
      - joypixels.sh
      - microsoft-fonts.sh
      - expressvpn.sh
      - teamviewer.sh
      # - dnsproxy.sh
      - papirus-icon-theme.sh
      - nanorc.sh
      - nix-installer.sh
      - depmod.sh
      # - bootc.sh
      # - selinux.sh

  - type: systemd
    system:
      enabled:
        # - tlp.service
        - tailscaled.service
        - fstrim.timer
        - btrfs-dedup@var-home.timer
        - usbguard.service
        - usbguard-dbus.service
        # - libvirtd.socket
        # - swtpm-workaround.service
        # - waydroid-workaround.service
        # - libvirt-workaround.service
        - mdatp.service
        - scx.service
        - dnscrypt-proxy.service
        # - docker.socket
      disabled:
        - raid-check.timer
        - systemd-homed.service
        - systemd-homed-activate.service
        - waydroid-container.service
        - systemd-resolved.service
    user:
      enabled:
        - fontconfig-cache.service
        - podman.socket
        # - appman-update.timer
        - openrazer-daemon.service

  - type: initramfs

  - type: signing
