# image will be published to ghcr.io/<user>/<name>
name: nhubaotruong-ublue
# description will be included in the image's metadata
description: nhubaotruong uBlue image

# the base image to build on top of (FROM) and the version tag to use
base-image: ghcr.io/ublue-os/silverblue-main
image-version: 40 # latest is also supported if you want new updates ASAP

# module configuration, executed in order
# you can include multiple instances of the same module
modules:
  - type: files
    files:
      - source: files
        destination: /

  # - type: copy
  #   from: docker.io/library/docker:cli
  #   src: /usr/local/libexec/docker/cli-plugins/docker-compose
  #   dest: /usr/bin/
  - type: containerfile
    snippets:
      - COPY --from=ghcr.io/ublue-os/fsync-kernel:40 /tmp/rpms /tmp/kernel-rpms
      - RUN rpm-ostree cliwrap install-to-root / && \
        rpm-ostree override replace --experimental \
        /tmp/kernel-rpms/kernel-[0-9]*.rpm \
        /tmp/kernel-rpms/kernel-core-*.rpm \
        /tmp/kernel-rpms/kernel-modules-*.rpm && \
        ostree container commit
    # containerfiles:
    #   - replace-kernel
    # - zfs-rpms
    # - upgrade
    # - match-kernel-version

  - type: akmods
    base: fsync
    install:
      - openrazer
      - v4l2loopback
      - xone
      - xpadneo

  - type: rpm-ostree
    repos:
      - https://raw.githubusercontent.com/coreos/fedora-coreos-config/testing-devel/fedora-coreos-pool.repo
      - https://copr.fedorainfracloud.org/coprs/atim/starship/repo/fedora-%OS_VERSION%/atim-starship-fedora-%OS_VERSION%.repo
      - https://copr.fedorainfracloud.org/coprs/ublue-os/staging/repo/fedora-%OS_VERSION%/ublue-os-staging-fedora-%OS_VERSION%.repo
      - https://copr.fedorainfracloud.org/coprs/ycollet/audinux/repo/fedora-%OS_VERSION%/ycollet-audinux-fedora-%OS_VERSION%.repo
      - https://copr.fedorainfracloud.org/coprs/kylegospo/bazzite/repo/fedora-%OS_VERSION%/kylegospo-bazzite-fedora-%OS_VERSION%.repo
      - https://copr.fedorainfracloud.org/coprs/kylegospo/system76-scheduler/repo/fedora-%OS_VERSION%/kylegospo-system76-scheduler-fedora-%OS_VERSION%.repo
      - https://copr.fedorainfracloud.org/coprs/ganto/lxc4/repo/fedora-%OS_VERSION%/ganto-lxc4-fedora-%OS_VERSION%.repo
      - https://download.opensuse.org/repositories/home:/lamlng/Fedora_%OS_VERSION%/home:lamlng.repo
      - https://pkgs.tailscale.com/stable/fedora/tailscale.repo
      - https://packages.microsoft.com/config/rhel/8/prod.repo
      # - https://copr.fedorainfracloud.org/coprs/secureblue/hardened_malloc/repo/fedora-%OS_VERSION%/secureblue-hardened_malloc-fedora-%OS_VERSION%.repo
      - https://copr.fedorainfracloud.org/coprs/kylegospo/bazzite-multilib/repo/fedora-%OS_VERSION%/kylegospo-bazzite-multilib-fedora-%OS_VERSION%.repo?arch=x86_64
      - https://copr.fedorainfracloud.org/coprs/rodoma92/rmlint/repo/fedora-%OS_VERSION%/rodoma92-rmlint-fedora-%OS_VERSION%.repo
      # - https://copr.fedorainfracloud.org/coprs/eyecantcu/supergfxctl/repo/fedora-%OS_VERSION%/eyecantcu-supergfxctl-fedora-%OS_VERSION%.repo
      # - https://raw.githubusercontent.com/nhubaotruong/nhubaotruong-ublue/main/config/repos/teamviewer.repo
      # - https://packages.microsoft.com/config/fedora/%OS_VERSION%/prod.repo
      # - https://download.docker.com/linux/fedora/docker-ce.repo
    install:
      - sqlite
      - starship
      - tilix
      - tilix-nautilus
      - gnome-tweaks
      # - file-roller
      - tlp
      # - lz4
      # - xz
      - zstd
      - ibus-bamboo
      - tailscale
      # - dconf-editor
      # - gnome-screenshot
      - breeze-cursor-theme
      - i2c-tools
      - ddcutil
      - virt-manager
      - libvirt
      - edk2-ovmf
      # - p7zip
      # - p7zip-plugins
      # - unrar
      # - bsdcat
      # - bsdcpio
      # - bsdtar
      # - bsdunzip
      - zram-generator
      - zsh
      - igt-gpu-tools
      - libgda
      - libgda-sqlite
      - firewall-config
      - dejavu-sans-fonts
      - dejavu-serif-fonts
      - system76-scheduler
      - gnome-shell-extension-system76-scheduler
      - gnome-shell-extension-gsconnect
      - liberation-fonts
      - ufraw
      - duperemove
      - rmlint
      - python3-icoextract
      - gnome-directory-thumbnailer
      - gnome-epub-thumbnailer
      - gnome-kra-ora-thumbnailer
      - waydroid
      - lxc
      - lxc-libs
      - cage
      - wlr-randr
      # - python3-pip
      - podman-docker
      - gstreamer1-vaapi
      - nautilus-open-any-terminal
      # - redhat-lsb-core
      # - libxcrypt-compat
      # - lzip
      - usbguard
      - usbguard-dbus
      - usbguard-tools
      # - gum
      - fuse-sshfs
      - openssh-askpass
      - nautilus-gsconnect
      - ifuse
      - libimobiledevice
      - usbmuxd
      - wl-clipboard
      - xclip
      - bindfs
      - gnome-network-displays
      - powertop
      - foo2zjs
      - teamviewer
      - mdatp
      # - hardened_malloc
      - ptyxis
      - bootc
      #- mesa-va-drivers-freeworld
      #- mesa-vdpau-drivers-freeworld.x86_64
      - libaacs
      - libbdplus
      - libbluray
      - rsms-inter-vf-fonts
    remove:
      - firefox # default firefox removed in favor of flatpak
      - firefox-langpacks # langpacks needs to also be removed to prevent dependency problems
      - power-profiles-daemon
      - yelp
      - gnome-tour
      - distrobox
      - toolbox
      - gnome-software
      - gnome-software-rpm-ostree
      - zram-generator-defaults
      - gnome-classic-session
      - gnome-classic-session-xsession
      - gnome-terminal
      - gnome-terminal-nautilus
    optfix:
      - teamviewer
      - microsoft
    replace:
      - from-repo: https://copr.fedorainfracloud.org/coprs/ublue-os/staging/repo/fedora-%OS_VERSION%/ublue-os-staging-fedora-%OS_VERSION%.repo
        packages:
          - mutter
          - mutter-common
          - gnome-shell
      - from-repo: https://copr.fedorainfracloud.org/coprs/kylegospo/bazzite-multilib/repo/fedora-%OS_VERSION%/kylegospo-bazzite-multilib-fedora-%OS_VERSION%.repo
        packages:
          - xorg-x11-server-Xwayland
      - from-repo: https://copr.fedorainfracloud.org/coprs/sentry/switcheroo-control_discrete/repo/fedora-%OS_VERSION%/sentry-switcheroo-control_discrete-fedora-%OS_VERSION%.repo
        packages:
          - switcheroo-control

  - from-file: flatpak.yml

  - type: gschema-overrides
    include:
      - zz1-desktop.gschema.override

  - type: fonts
    fonts:
      nerd-fonts:
        - FiraCode
        - Meslo
        - CascadiaCode
      google-fonts:
        # - Roboto

  # - type: yafti # if included, yafti and it's dependencies (pip & libadwaita) will be installed and set up
  #   custom-flatpaks:
  # this section is optional
  # - Celluloid: io.github.celluloid_player.Celluloid
  # - Krita: org.kde.krita

  - type: bling # configure what to pull in from ublue-os/bling
    install:
      - ublue-update # https://github.com/ublue-os/ublue-update
      # - dconf-update-service # a service unit that updates the dconf db on boot
      - laptop

  - type: gnome-extensions
    install:
      - 615 # AppIndicator and KStatusNotifierItem Support
      # - 1319 # GSConnect
      - 19 # User Themes
      - 307 # Dash to Dock
      - 7 # Removable Drive Menu
      - 3843 # Just Perfection
      - 517 # Caffeine
      - 4269 # Alphabetical App Grid
      - 2594 # Always Indicator
      # - 5425 # Battery Time
      - 6670 # Bluetooth Battery Meter
      - 2645 # Brightness Control Using ddcutil
      - 1873 # Disable Unredirect Fullscreen Windows
      # - 4485 # Favourites In AppGrid
      # - 4158 # Gnome 4x UI Improvements
      - 3956 # Gnome fuzzy app search
      - 6940 # Media Progress
      # - 5278 # Pano Clipboard Manager
      - 4691 # Pip on top
      - 5964 # Quick Settings Audio Devices Hider
      - 5660 # Weather Or Not

  - type: brew
    brew-analytics: false

  - type: script
    scripts:
      - distrobox.sh
      - microsoft-fonts.sh
      - expressvpn.sh
      - nanorc.sh
      - papirus-icon-theme.sh
      - depmod.sh
      - initramfs.sh
      - bootc.sh
      # - selinux.sh

  - type: systemd
    system:
      enabled:
        - tlp.service
        - tailscaled.service
        - fstrim.timer
        - com.system76.Scheduler.service
        - btrfs-dedup@var-home.timer
        - usbguard.service
        - usbguard-dbus.service
        - swtpm-workaround.service
        - waydroid-workaround.service
        - mdatp.service
        # - docker.socket
      disabled:
        - raid-check.timer
        - systemd-homed.service
        - systemd-homed-activate.service
        - waydroid-container.service
    user:
      enabled:
        - fontconfig-cache.service
        - podman.socket
        - appman-update.timer
      disabled:

  - type: signing
