# image will be published to ghcr.io/<user>/<name>
name: nhubaotruong-ublue
# description will be included in the image's metadata
description: nhubaotruong uBlue image

# the base image to build on top of (FROM) and the version tag to use
base-image: ghcr.io/ublue-os/silverblue-main
image-version: 42 # latest is also supported if you want new updates ASAP

# module configuration, executed in order
# you can include multiple instances of the same module
modules:
  - type: files
    files:
      - source: files
        destination: /

  - type: script
    snippets:
      - rm /usr/share/thumbnailers/avif.thumbnailer

  # - type: containerfile
  #   containerfiles:
  #     - replace-kernel
      # - install-akmods
      # - zfs-rpms
  # - upgrade
  # - match-kernel-version

  # - type: dnf
  #   source: ghcr.io/blue-build/modules/dnf:dnf-module
  #   install:
  #     - https://mirrors.rpmfusion.org/free/fedora/rpmfusion-free-release-%OS_VERSION%.noarch.rpm
  #     - https://mirrors.rpmfusion.org/nonfree/fedora/rpmfusion-nonfree-release-%OS_VERSION%.noarch.rpm

  - type: akmods
    base: main
    install:
      # - openrazer
      - v4l2loopback
      - xone
      - xpadneo
      # - VirtualBox

  - type: dnf
    source: ghcr.io/blue-build/modules/dnf:dnf-module
    nonfree: negativo17
    repos:
      cleanup: true
      files:
        # - https://raw.githubusercontent.com/coreos/fedora-coreos-config/testing-devel/fedora-coreos-pool.repo
        - https://download.opensuse.org/repositories/home:/lamlng/Fedora_Rawhide/home:lamlng.repo
        # - https://openrazer.github.io/hardware:razer.repo
        - https://pkgs.tailscale.com/stable/fedora/tailscale.repo
        - https://packages.microsoft.com/config/rhel/8/insiders-slow.repo
      copr:
        - atim/starship
        - ublue-os/packages
        - ublue-os/staging
        - ycollet/audinux
        - bazzite-org/bazzite
        - bazzite-org/bazzite-multilib
        - ganto/lxc4
        - bieszczaders/kernel-cachyos-addons
        - trixieua/mutter-patched
    install:
      packages:
        - sqlite
        - starship
        - gnome-tweaks
        - neovim
        - zstd
        - ibus-bamboo
        - ibus-unikey
        - tailscale
        - breeze-cursor-theme
        - i2c-tools
        - ddcutil
        - qemu-user-binfmt
        - qemu-user-static
        - edk2-ovmf
        - zram-generator
        - zsh
        - igt-gpu-tools
        - libgda
        - libgda-sqlite
        - firewall-config
        - dejavu-sans-fonts
        - dejavu-serif-fonts
        - liberation-fonts
        - ufraw
        - duperemove
        - rmlint
        - python3-icoextract
        - gnome-directory-thumbnailer
        - gnome-epub-thumbnailer
        - gnome-kra-ora-thumbnailer
        - waydroid
        - lxc
        - lxc-libs
        - cage
        - wlr-randr
        - nautilus-open-any-terminal
        - fuse-sshfs
        - openssh-askpass
        - nautilus-gsconnect
        - ifuse
        - libimobiledevice
        - usbmuxd
        - wl-clipboard
        - xclip
        - bindfs
        - powertop
        - foo2zjs
        - mdatp
        - bootc
        - rsms-inter-vf-fonts
        - cpulimit
        - kernel-tools
        - scx-scheds
        - fontawesome-fonts-all
        - profile-cleaner
        - samba-dcerpc
        - samba-ldb-ldap-modules
        - samba-winbind-clients
        - samba-winbind-modules
        - samba
        - yq
        - printer-driver-brlaser
        - epson-inkjet-printer-escpr
        - epson-inkjet-printer-escpr2
        - dnscrypt-proxy
        - openresolv
        - python-pysocks
        # - openrazer-daemon
        # - python3-openrazer
        - fuse-btfs
        - mimalloc
        - papirus-icon-theme-dark
        - ublue-os-media-automount-udev
        - adwaita++-icons
        - meslo-nerd-fonts
        - firacode-nerd-fonts
        # Gnome extensions
        - gnome-shell-extension-gsconnect
        # - gnome-shell-extension-appindicator
        # - gnome-shell-extension-user-theme
        # - gnome-shell-extension-dash-to-dock
        # - gnome-shell-extension-just-perfection
        # - gnome-shell-extension-caffeine
    remove:
      auto-remove: true
      packages:
        - firefox # default firefox removed in favor of flatpak
        - firefox-langpacks # langpacks needs to also be removed to prevent dependency problems
        - yelp
        - gnome-tour
        - toolbox
        - gnome-software
        - zram-generator-defaults
        - gnome-classic-session
        - thermald
        - systemd-networkd
        - ptyxis
    optfix:
      - teamviewer
      - microsoft
    replace:
      - from-repo: copr:copr.fedorainfracloud.org:trixieua:mutter-patched
        packages:
          - gdm
          - mutter
          - mutter-common
          - gnome-shell
          - xorg-x11-server-Xwayland
      - from-repo: terra-extras
        packages:
          - switcheroo-control
      # - from-repo: https://copr.fedorainfracloud.org/coprs/terra-extras/switcheroo-control_discrete/repo/fedora-%OS_VERSION%/sentry-switcheroo-control_discrete-fedora-%OS_VERSION%.repo
      #   packages:
      #     - switcheroo-control

  - from-file: flatpak.yml

  - type: gschema-overrides
    include:
      - zz1-desktop.gschema.override

  # - type: fonts
  #   fonts:
  #     nerd-fonts:
  #       - FiraCode
  #       - Meslo
  #       - CascadiaCode

  # - type: yafti # if included, yafti and it's dependencies (pip & libadwaita) will be installed and set up
  #   custom-flatpaks:
  # this section is optional
  # - Celluloid: io.github.celluloid_player.Celluloid
  # - Krita: org.kde.krita

  # - type: bling # configure what to pull in from ublue-os/bling
  #   install:
  #     - ublue-update # https://github.com/ublue-os/ublue-update

  - type: gnome-extensions
    install:
      - "615" # AppIndicator and KStatusNotifierItem Support
      # - "1319" # GSConnect
      - "19" # User Themes
      - "307" # Dash to Dock
      - "7" # Removable Drive Menu
      - "3843" # Just Perfection
      - "517" # Caffeine
      - "4269" # Alphabetical App Grid
      - "2594" # Always Indicator
      # - "5425" # Battery Time
      - "6670" # Bluetooth Battery Meter
      - "2645" # Brightness Control Using ddcutil
      # - "1873" # Disable Unredirect Fullscreen Windows
      # - "4485" # Favourites In AppGrid
      # - "4158" # Gnome 4x UI Improvements
      - "3956" # Gnome fuzzy app search
      - "6940" # Media Progress
      # - "5278" # Pano Clipboard Manager
      - "4691" # Pip on top
      - "5964" # Quick Settings Audio Devices Hider
      - "5660" # Weather Or Not
      - "4798" # Thinkpad Battery Threshold
      - "6807" # System Monitor
      - "3193" # Blur My Shell
      - "7652" # Pipewire Raop Discover (AirPlay)
      - "7837" # HDR Auto Enable

  # - type: brew
  #   brew-analytics: false

  - type: script
    scripts:
      - byedpi.sh
      - joypixels.sh
      - microsoft-fonts.sh
      - teamviewer.sh
      - nanorc.sh
      - nix-installer.sh
      - bazzite.sh
      - depmod.sh

  - type: systemd
    system:
      enabled:
        # - tlp.service
        - tailscaled.service
        - fstrim.timer
        - btrfs-dedup@var-home.timer
        # - libvirtd.socket
        # - swtpm-workaround.service
        # - waydroid-workaround.service
        # - libvirt-workaround.service
        - mdatp.service
        - scx.service
        - dnscrypt-proxy.service
        # - docker.socket
      disabled:
        - raid-check.timer
        - systemd-homed.service
        - systemd-homed-activate.service
        - waydroid-container.service
        - systemd-resolved.service
    user:
      enabled:
        - fontconfig-cache.service
        - podman.socket
        # - appman-update.timer
        # - openrazer-daemon.service

  - type: initramfs

  - type: signing
