# image will be published to ghcr.io/<user>/<name>
name: nhubaotruong-ublue
# description will be included in the image's metadata
description: nhubaotruong uBlue image

# the base image to build on top of (FROM) and the version tag to use
base-image: ghcr.io/ublue-os/silverblue-main
image-version: 40 # latest is also supported if you want new updates ASAP

# module configuration, executed in order
# you can include multiple instances of the same module
modules:
  - type: files
    files:
      - usr: /usr
      - etc: /etc

  - type: containerfile
    containerfiles:
      - upgrade
      - match-kernel-version

  - type: rpm-ostree
    repos:
      - https://raw.githubusercontent.com/coreos/fedora-coreos-config/testing-devel/fedora-coreos-pool.repo
      - https://copr.fedorainfracloud.org/coprs/atim/starship/repo/fedora-%OS_VERSION%/atim-starship-fedora-%OS_VERSION%.repo
      - https://copr.fedorainfracloud.org/coprs/ublue-os/staging/repo/fedora-%OS_VERSION%/ublue-os-staging-fedora-%OS_VERSION%.repo
      - https://copr.fedorainfracloud.org/coprs/ycollet/audinux/repo/fedora-%OS_VERSION%/ycollet-audinux-fedora-%OS_VERSION%.repo
      - https://copr.fedorainfracloud.org/coprs/kylegospo/hl2linux-selinux/repo/fedora-%OS_VERSION%/kylegospo-hl2linux-selinux-fedora-%OS_VERSION%.repo
      - https://copr.fedorainfracloud.org/coprs/kylegospo/bazzite/repo/fedora-%OS_VERSION%/kylegospo-bazzite-fedora-%OS_VERSION%.repo
      - https://copr.fedorainfracloud.org/coprs/kylegospo/system76-scheduler/repo/fedora-%OS_VERSION%/kylegospo-system76-scheduler-fedora-%OS_VERSION%.repo
      - https://copr.fedorainfracloud.org/coprs/ganto/lxc4/repo/fedora-%OS_VERSION%/ganto-lxc4-fedora-%OS_VERSION%.repo
      - https://download.opensuse.org/repositories/home:/lamlng/Fedora_%OS_VERSION%/home:lamlng.repo
      - https://pkgs.tailscale.com/stable/fedora/tailscale.repo
      - https://packages.microsoft.com/config/rhel/8/prod.repo
      - https://copr.fedorainfracloud.org/coprs/secureblue/hardened_malloc/repo/fedora-%OS_VERSION%/secureblue-hardened_malloc-fedora-%OS_VERSION%.repo
      - https://copr.fedorainfracloud.org/coprs/kylegospo/bazzite-multilib/repo/fedora-%OS_VERSION%/kylegospo-bazzite-multilib-fedora-%OS_VERSION%.repo?arch=x86_64
      # - https://copr.fedorainfracloud.org/coprs/eyecantcu/supergfxctl/repo/fedora-%OS_VERSION%/eyecantcu-supergfxctl-fedora-%OS_VERSION%.repo
      # - https://raw.githubusercontent.com/nhubaotruong/nhubaotruong-ublue/main/config/repos/teamviewer.repo
      # - https://packages.microsoft.com/config/fedora/%OS_VERSION%/prod.repo
      # - https://download.docker.com/linux/fedora/docker-ce.repo
    install:
      - sqlite
      - starship
      - tilix
      - tilix-nautilus
      - gnome-tweaks
      - file-roller
      - tlp
      - lz4
      - xz
      - zstd
      - ibus-bamboo
      - tailscale
      - dconf-editor
      - gnome-screenshot
      - breeze-cursor-theme
      - i2c-tools
      - ddcutil
      - virt-manager
      - libvirt
      - edk2-ovmf
      - p7zip
      - p7zip-plugins
      - unrar
      - bsdcat
      - bsdcpio
      - bsdtar
      - bsdunzip
      - zram-generator
      - zsh
      - igt-gpu-tools
      - libgda
      - libgda-sqlite
      - firewall-config
      - dejavu-sans-fonts
      - dejavu-serif-fonts
      - lsd
      - minizip-ng-compat # fedora 40
      - minizip-ng
      - qt5-qtquickcontrols
      - system76-scheduler
      - gnome-shell-extension-system76-scheduler
      - hl2linux-selinux
      - python3-psutil
      - libnotify
      - binutils
      # - libadwaita-devel
      # - pygobject3-devel
      - liberation-fonts
      - ufraw
      - duperemove
      - rmlint
      - podman-compose
      - python3-icoextract
      - gnome-directory-thumbnailer
      - gnome-epub-thumbnailer
      - gnome-kra-ora-thumbnailer
      - waydroid
      - lxc
      - lxc-libs
      - cage
      - wlr-randr
      - python3-pip
      - podman-docker
      - gstreamer1-vaapi
      - nautilus-open-any-terminal
      - redhat-lsb-core
      - libxcrypt-compat
      - lzip
      - usbguard
      - usbguard-dbus
      - usbguard-tools
      - gum
      - fuse-sshfs
      - openssh-askpass
      - nautilus-gsconnect
      - ifuse
      - libimobiledevice
      - usbmuxd
      - wl-clipboard
      - xclip
      - bindfs
      - gnome-network-displays
      - powertop
      - gnome-shell-extension-gsconnect
      - foo2zjs
      - papirus-icon-theme-dark
      - teamviewer
      - mdatp
      - hardened_malloc
      - gamescope
    remove:
      - firefox # default firefox removed in favor of flatpak
      - firefox-langpacks # langpacks needs to also be removed to prevent dependency problems
      - power-profiles-daemon
      - yelp
      - gnome-tour
      # - distrobox
      - toolbox
      - gnome-software
      - gnome-software-rpm-ostree
      - zram-generator-defaults
      - gnome-classic-session
      - gnome-classic-session-xsession
      - gnome-terminal
      - gnome-terminal-nautilus
    optfix:
      - teamviewer
      - microsoft

  - from-file: flatpak.yml

  - type: gschema-overrides
    include:
      - zz1-desktop.gschema.override

  - type: fonts
    fonts:
      nerd-fonts:
        - FiraCode
        - Meslo
        - CascadiaCode
      google-fonts:
        # - Roboto

  # - type: yafti # if included, yafti and it's dependencies (pip & libadwaita) will be installed and set up
  #   custom-flatpaks:
  # this section is optional
  # - Celluloid: io.github.celluloid_player.Celluloid
  # - Krita: org.kde.krita

  - type: akmods
    base: main
    install:
      - v4l2loopback
      - xone
      - xpadneo

  - type: bling # configure what to pull in from ublue-os/bling
    install:
      - ublue-update # https://github.com/ublue-os/ublue-update
      # - dconf-update-service # a service unit that updates the dconf db on boot
      - laptop

  - type: gnome-extensions
    install:
      - 615 # AppIndicator and KStatusNotifierItem Support
      # - 1319 # GSConnect
      - 19 # User Themes
      - 307 # Dash to Dock
      - 7 # Removable Drive Menu
      - 3843 # Just Perfection
      - 517 # Caffeine
      - 4269 # Alphabetical App Grid
      - 2594 # Always Indicator
      # - 5425 # Battery Time
      - 6670 # Bluetooth Battery Meter
      - 2645 # Brightness Control Using ddcutil
      - 1873 # Disable Unredirect Fullscreen Windows
      # - 4485 # Favourites In AppGrid
      - 4158 # Gnome 4x UI Improvements
      - 3956 # Gnome fuzzy app search
      - 6940 # Media Progress
      # - 5278 # Pano Clipboard Manager
      - 4691 # Pip on top
      - 5964 # Quick Settings Audio Devices Hider
      - 5660 # Weather Or Not

  - type: script
    scripts:
      # - hardened-malloc.sh
      # - distrobox.sh
      - mutter-triple-patch.sh
      # - gnome-vrr.sh
      - microsoft-fonts.sh
      # - dnsproxy.sh
      # - teamviewer.sh
      - expressvpn.sh
      # - mdatp.sh
      - nanorc.sh
      # - papirus-icon-theme.sh
      - bazzite.sh
      - waydroid.sh
      - prompt.sh
      - docker-compose.sh
      # - zapret.sh
      - workarounds.sh
      - initramfs.sh
      # - selinux.sh

  - type: systemd
    system:
      enabled:
        - tlp.service
        - tailscaled.service
        - fstrim.timer
        - com.system76.Scheduler.service
        - btrfs-dedup@var-home.timer
        - usbguard.service
        - usbguard-dbus.service
        - swtpm-workaround.service
        - waydroid-workaround.service
        - mdatp.service
        # - docker.socket
      disabled:
        - raid-check.timer
        - systemd-homed.service
        - systemd-homed-activate.service
    user:
      enabled:
        - fontconfig-cache.service
        - podman.socket
      disabled:

  - type: signing
