COPY --from=ghcr.io/ublue-os/fsync-kernel:40 /tmp/rpms /tmp/fsync-rpms
RUN rpm-ostree cliwrap install-to-root / && \
    rpm-ostree override replace \
    --experimental \
    /tmp/fsync-rpms/kernel-[0-9]*.rpm \
    /tmp/fsync-rpms/kernel-core-*.rpm \
    /tmp/fsync-rpms/kernel-modules-*.rpm \
    /tmp/fsync-rpms/kernel-uki-virt-*.rpm && \
    ostree container commit