- type: default-flatpaks
  notify: true
  system:
    install:
      - com.brave.Browser
      - com.getpostman.Postman
      - com.github.johnfactotum.Foliate
      - com.github.tchx84.Flatseal
      - com.heroicgameslauncher.hgl
      - com.ktechpit.torrhunt
      - com.mattjakeman.ExtensionManager
      - com.obsproject.Studio
      - com.obsproject.Studio.Plugin.Gstreamer
      - com.obsproject.Studio.Plugin.GStreamerVaapi
      - org.gtk.Gtk3theme.adw-gtk3
      - org.gtk.Gtk3theme.adw-gtk3-dark
      - com.usebottles.bottles
      - com.valvesoftware.Steam
      - com.valvesoftware.Steam.Utility.steamtinkerlaunch
      - com.vysp3r.ProtonPlus
      - fyi.zoey.Boop-GTK
      - io.github.Foldex.AdwSteamGtk
      - io.github.tdesktop_x64.TDesktop
      - io.github.vikdevelop.SaveDesktop
      - org.filezillaproject.Filezilla
      - org.gnome.Calculator
      - org.gnome.Calendar
      - org.gnome.Characters
      - org.gnome.clocks
      - org.gnome.Contacts
      - org.gnome.DejaDup
      - org.gnome.Epiphany
      - org.gnome.Evince
      - org.gnome.font-viewer
      - org.gnome.gThumb
      - org.gnome.Loupe
      - org.gnome.Loupe.HEIC
      - org.gnome.NautilusPreviewer
      - org.gnome.TextEditor
      - org.gnome.Weather
      - org.jdownloader.JDownloader
      - org.libreoffice.LibreOffice
      - org.qbittorrent.qBittorrent
      - org.videolan.VLC
      - xyz.armcord.ArmCord
      - one.ablaze.floorp
      - com.github.eneshecan.WhatsAppForLinux
