# image will be published to ghcr.io/<user>/<name>
name: nhubaotruong-ublue
# description will be included in the image's metadata
description: nhubaotruong uBlue image

# the base image to build on top of (FROM) and the version tag to use
base-image: ghcr.io/ublue-os/silverblue-nvidia
image-version: 39 # latest is also supported if you want new updates ASAP

# module configuration, executed in order
# you can include multiple instances of the same module
modules:
  - type: files
    files:
      - usr:
          /usr # copy static configurations
          #
          # copies config/files/usr into your image's /usr
          #
          # configuration you wish to end up in /etc/ on the booted system
          # should be added into /usr/etc/ as that is the proper "distro"
          # config directory on ostree. Read more in the files module's README

  - type: rpm-ostree
    repos:
      - https://copr.fedorainfracloud.org/coprs/atim/starship/repo/fedora-%OS_VERSION%/atim-starship-fedora-%OS_VERSION%.repo
      - https://copr.fedorainfracloud.org/coprs/ublue-os/distrobox-git/repo/fedora-%OS_VERSION%/ublue-os-distrobox-git-fedora-%OS_VERSION%.repo
      - https://copr.fedorainfracloud.org/coprs/kylegospo/hl2linux-selinux/repo/fedora-%OS_VERSION%/kylegospo-hl2linux-selinux-fedora-%OS_VERSION%.repo
      - https://copr.fedorainfracloud.org/coprs/kylegospo/system76-scheduler/repo/fedora-%OS_VERSION%/kylegospo-system76-scheduler-fedora-%OS_VERSION%.repo
      - https://download.opensuse.org/repositories/home:lamlng/Fedora_%OS_VERSION%/home:lamlng.repo
      - https://pkgs.tailscale.com/stable/fedora/tailscale.repo
    install:
      - starship
      - tilix
      - tilix-nautilus
      - gnome-tweaks
      - file-roller
      - tlp
      - lz4
      - xz
      - zstd
      - papirus-icon-theme
      - ibus-bamboo
      - tailscale
      - dconf-editor
      - gnome-screenshot
      - breeze-cursor-theme
      - i2c-tools
      - ddcutil
      - virt-manager
      - libvirt
      - edk2-ovmf
      - powertop
      - p7zip
      - p7zip-plugins
      - unrar
      - bsdcat
      - bsdcpio
      - bsdtar
      - bsdunzip
      - ffmpegthumbnailer
      - zram-generator
      - zsh
      - igt-gpu-tools
      - libgda
      - libgda-sqlite
      - firewall-config
      - dejavu-sans-fonts
      - dejavu-serif-fonts
      - lsd
      - minizip-compat
      - minizip-ng
      - qt5-qtquickcontrols
      - distrobox-git
      - system76-scheduler
      - hl2linux-selinux
      - python3-psutil
      - libnotify
      - binutils
      - libadwaita-devel
      - pygobject3-devel
      - liberation-fonts
      - ufraw
      - google-noto-fonts
      - gnome-directory-thumbnailer
      - gnome-epub-thumbnailer
      - gnome-kra-ora-thumbnailer
      - gnome-shell-extension-appindicator
      - gnome-shell-extension-gsconnect
      - gnome-shell-extension-user-theme
      - gnome-shell-extension-dash-to-dock
      - gnome-shell-extension-drive-menu
      # - gnome-shell-extension-no-overview
      - gnome-shell-extension-just-perfection
      - gnome-shell-extension-caffeine
      - gnome-shell-extension-supergfxctl-gex
      - gnome-shell-extension-system76-scheduler
    remove:
      - firefox # default firefox removed in favor of flatpak
      - firefox-langpacks # langpacks needs to also be removed to prevent dependency problems
      - power-profiles-daemon
      - yelp
      - gnome-tour
      - toolbox
      - distrobox
      - gnome-software
      - gnome-software-rpm-ostree
      - zram-generator-defaults
      - gnome-classic-session
      - gnome-terminal
      - gnome-terminal-nautilus

  - type: fonts
    fonts:
      nerd-fonts:
        - FiraCode
        - Meslo
        - CascadiaCode
      google-fonts:
        - Roboto

  # - type: yafti # if included, yafti and it's dependencies (pip & libadwaita) will be installed and set up
  #   custom-flatpaks:
  # this section is optional
  # - Celluloid: io.github.celluloid_player.Celluloid
  # - Krita: org.kde.krita

  - type: script
    scripts:
      # this sets up the proper policy & signing files for signed images to work
      - signing.sh
      # - nerd-fonts.sh
      # - thorium.sh
      - mutter-triple-patch.sh
      - microsoft-fonts.sh
      - dnsproxy.sh
      - teamviewer.sh
      - expressvpn.sh
      - mdatp.sh
      - nanorc.sh

  - type: bling # configure what to pull in from ublue-os/bling
    install:
      # - fonts # selection of common good free fonts
      - justfiles # add "!include /usr/share/ublue-os/just/bling.just"
        # in your custom.just (added by default) or local justfile
      # - nix-installer # shell shortcuts for determinate system's nix installers
      # - ublue-os-wallpapers
      - ublue-update # https://github.com/ublue-os/ublue-update
      - dconf-update-service # a service unit that updates the dconf db on boot
      - laptop
      # - devpod # https://devpod.sh/ as an rpm

  - type: systemd
    system:
      enabled:
        - tlp.service
        - supergfxd.service
        - tailscaled.service
        - fstrim.timer
        - com.system76.Scheduler.service
      disabled:
        - raid-check.timer
    user:
      enabled:
        # - fontconfig-clear.service
        # - start-distrobox.service
      disabled:
