# image will be published to ghcr.io/<user>/<name>
name: nhubaotruong-ublue
# description will be included in the image's metadata
description: nhubaotruong uBlue image

# the base image to build on top of (FROM) and the version tag to use
base-image: ghcr.io/ublue-os/silverblue-nvidia
image-version: 39 # latest is also supported if you want new updates ASAP

# module configuration, executed in order
# you can include multiple instances of the same module
modules:
  - type: files
    files:
      - usr:
          /usr # copy static configurations
          #
          # copies config/files/usr into your image's /usr
          #
          # configuration you wish to end up in /etc/ on the booted system
          # should be added into /usr/etc/ as that is the proper "distro"
          # config directory on ostree. Read more in the files module's README

  - type: rpm-ostree
    repos:
      - https://copr.fedorainfracloud.org/coprs/atim/starship/repo/fedora-%OS_VERSION%/atim-starship-fedora-%OS_VERSION%.repo
      - https://copr.fedorainfracloud.org/coprs/ublue-os/staging/repo/fedora-%OS_VERSION%/ublue-os-staging-fedora-%OS_VERSION%.repo
      - https://copr.fedorainfracloud.org/coprs/ycollet/audinux/repo/fedora-%OS_VERSION%/ycollet-audinux-fedora-%OS_VERSION%.repo
      - https://copr.fedorainfracloud.org/coprs/kylegospo/hl2linux-selinux/repo/fedora-%OS_VERSION%/kylegospo-hl2linux-selinux-fedora-%OS_VERSION%.repo
      - https://copr.fedorainfracloud.org/coprs/kylegospo/bazzite/repo/fedora-%OS_VERSION%/kylegospo-bazzite-fedora-%OS_VERSION%.repo
      # - https://copr.fedorainfracloud.org/coprs/kylegospo/system76-scheduler/repo/fedora-%OS_VERSION%/kylegospo-system76-scheduler-fedora-%OS_VERSION%.repo
      - https://copr.fedorainfracloud.org/coprs/mikelo2/gnome-network-displays/repo/fedora-%OS_VERSION%/mikelo2-gnome-network-displays-fedora-%OS_VERSION%.repo
      - https://copr.fedorainfracloud.org/coprs/ganto/lxc4/repo/fedora-39/ganto-lxc4-fedora-39.repo
      - https://download.opensuse.org/repositories/home:lamlng/Fedora_%OS_VERSION%/home:lamlng.repo
      - https://pkgs.tailscale.com/stable/fedora/tailscale.repo
      - https://raw.githubusercontent.com/ublue-os/bluefin/main/etc/yum.repos.d/charm.repo
      # - https://raw.githubusercontent.com/nhubaotruong/nhubaotruong-ublue/main/config/repos/teamviewer.repo
      # - https://packages.microsoft.com/config/fedora/%OS_VERSION%/prod.repo
      # - https://download.docker.com/linux/fedora/docker-ce.repo
    install:
      - sqlite
      - starship
      - tilix
      - tilix-nautilus
      - gnome-tweaks
      - file-roller
      # - tlp
      - lz4
      - xz
      - zstd
      - ibus-bamboo
      - tailscale
      - dconf-editor
      - gnome-screenshot
      - breeze-cursor-theme
      - i2c-tools
      - ddcutil
      - virt-manager
      - libvirt
      - edk2-ovmf
      - p7zip
      - p7zip-plugins
      - unrar
      - bsdcat
      - bsdcpio
      - bsdtar
      - bsdunzip
      - zram-generator
      - zsh
      - igt-gpu-tools
      - libgda
      - libgda-sqlite
      - firewall-config
      - dejavu-sans-fonts
      - dejavu-serif-fonts
      - lsd
      - minizip-compat
      - minizip-ng
      - qt5-qtquickcontrols
      # - system76-scheduler
      - hl2linux-selinux
      - python3-psutil
      - libnotify
      - binutils
      # - libadwaita-devel
      # - pygobject3-devel
      - liberation-fonts
      - ufraw
      - duperemove
      - rmlint
      - podman-compose
      - python3-icoextract
      - gnome-directory-thumbnailer
      - gnome-epub-thumbnailer
      - gnome-kra-ora-thumbnailer
      - gnome-shell-extension-appindicator
      - gnome-shell-extension-gsconnect
      - gnome-shell-extension-user-theme
      - gnome-shell-extension-dash-to-dock
      - gnome-shell-extension-drive-menu
      # - gnome-shell-extension-no-overview
      - gnome-shell-extension-just-perfection
      - gnome-shell-extension-caffeine
      - supergfxctl
      - gnome-shell-extension-supergfxctl-gex
      # - gnome-shell-extension-system76-scheduler
      - waydroid
      - lxc
      - lxc-libs
      - cage
      - wlr-randr
      - python3-pip
      - podman-docker
      - gnome-network-displays
      - gstreamer1-vaapi
      - nautilus-open-any-terminal
      - redhat-lsb-core
      - libxcrypt-compat
      - lzip
      - usbguard
      - usbguard-dbus
      - usbguard-tools
      - gum
      - fuse-sshfs
      - openssh-askpass
      - nautilus-gsconnect
      - ifuse
      - libimobiledevice
      - usbmuxd
      - wl-clipboard
      - xclip
      - tuned
      - tuned-ppd
      - tuned-utils
      - tuned-profiles-atomic
      - bindfs
      # - teamviewer
      # - mdatp
    remove:
      - firefox # default firefox removed in favor of flatpak
      - firefox-langpacks # langpacks needs to also be removed to prevent dependency problems
      - power-profiles-daemon
      - yelp
      - gnome-tour
      - toolbox
      - gnome-software
      - gnome-software-rpm-ostree
      - zram-generator-defaults
      - gnome-classic-session
      - gnome-terminal
      - gnome-terminal-nautilus

  - from-file: flatpak.yml

  - type: fonts
    fonts:
      nerd-fonts:
        - FiraCode
        - Meslo
        - CascadiaCode
      google-fonts:
        - Roboto

  # - type: yafti # if included, yafti and it's dependencies (pip & libadwaita) will be installed and set up
  #   custom-flatpaks:
  # this section is optional
  # - Celluloid: io.github.celluloid_player.Celluloid
  # - Krita: org.kde.krita

  - type: akmods
    base: main
    install:
      - v4l2loopback
      - xone
      - xpadneo
      - evdi
      - openrazer
      - winesync

  - type: bling # configure what to pull in from ublue-os/bling
    install:
      - ublue-update # https://github.com/ublue-os/ublue-update
      - dconf-update-service # a service unit that updates the dconf db on boot
      # - laptop

  - type: script
    scripts:
      # - hardened-malloc.sh
      - mutter-triple-patch.sh
      # - gnome-vrr.sh
      - microsoft-fonts.sh
      # - dnsproxy.sh
      - teamviewer.sh
      - expressvpn.sh
      - mdatp.sh
      - nanorc.sh
      - papirus-icon-theme.sh
      - bazzite.sh
      - waydroid.sh
      - prompt.sh
      - docker-compose.sh
      - workarounds.sh
      - selinux.sh

  - type: systemd
    system:
      enabled:
        - tuned.service
        - supergfxd.service
        - tailscaled.service
        - fstrim.timer
        # - com.system76.Scheduler.service
        - btrfs-dedup@var-home.timer
        - usbguard.service
        - usbguard-dbus.service
        - swtpm-workaround.service
        - waydroid-workaround.service
        # - docker.socket
      disabled:
        - raid-check.timer
        - systemd-homed.service
        - systemd-homed-activate.service
    user:
      enabled:
        - fontconfig-cache.service
      disabled:

  - type: signing
