RUN --mount=type=bind,from=ghcr.io/ublue-os/akmods:coreos-stable-41,source=/rpms/kmods,target=/tmp/rpms \
    rpm-ostree cliwrap install-to-root / && \
    rpm-ostree install \
    https://mirrors.rpmfusion.org/free/fedora/rpmfusion-free-release-$(rpm -E %fedora).noarch.rpm \
    https://mirrors.rpmfusion.org/nonfree/fedora/rpmfusion-nonfree-release-$(rpm -E %fedora).noarch.rpm && \
    rpm-ostree install \ 
    /tmp/rpms/kmod-openrazer-*.rpm \
    /tmp/rpms/kmod-v4l2loopback-*.rpm \
    /tmp/rpms/kmod-xone-*.rpm && \
    ostree container commit