RUN --mount=type=bind,from=ghcr.io/ublue-os/akmods:coreos-stable-43,source=/kernel-rpms,target=/tmp/kernel-rpms \
    rpm --erase kernel --nodeps && \
    rpm --erase kernel-core --nodeps && \
    rpm --erase kernel-modules --nodeps && \
    rpm --erase kernel-modules-core --nodeps && \
    rpm --erase kernel-modules-extra --nodeps && \
    dnf5 -y install \
    /tmp/kernel-rpms/kernel-[0-9]*.rpm \
    /tmp/kernel-rpms/kernel-core-*.rpm \
    /tmp/kernel-rpms/kernel-modules-*.rpm \
    /tmp/kernel-rpms/kernel-devel-*.rpm && \
    dnf5 versionlock add kernel kernel-devel kernel-devel-matched kernel-core kernel-modules kernel-modules-core kernel-modules-extra
