RUN --mount=type=bind,from=ghcr.io/ublue-os/coreos-testing-kernel:41,source=/tmp/rpms,target=/tmp/kernel-rpms \
    rpm-ostree cliwrap install-to-root / && \
    rpm-ostree override replace --experimental \
    /tmp/kernel-rpms/kernel-[0-9]*.rpm \
    /tmp/kernel-rpms/kernel-core-*.rpm \
    /tmp/kernel-rpms/kernel-modules-*.rpm && \
    ostree container commit