name: bluebuild
on:
  schedule:
    - cron: "30 3 * * *"
  push:
    paths-ignore: # don't rebuild if only documentation has changed
      - "**.md"
      - ".github/workflows/cleanup*.yml"

  pull_request:
  workflow_dispatch: # allow manually triggering builds

# Add concurrency configuration
concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: true

jobs:
  bluebuild:
    name: Build Custom Image
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      id-token: write
    strategy:
      fail-fast: false # stop GH from cancelling all matrix builds if one fails
      matrix:
        recipe:
          # !! Add your recipes here
          - recipe.yml
    steps:
      - name: Build Custom Image
        uses: blue-build/github-action@v1
        with:
          recipe: ${{ matrix.recipe }}
          cosign_private_key: ${{ secrets.SIGNING_SECRET }}
          registry_token: ${{ github.token }}
          pr_event_number: ${{ github.event.number }}
          rechunk: "true"
          use_cache: "true"
          maximize_build_space: "false"
